### ISSUE TITLE
Under macOS 15, your program has a bug. After restarting the computer, there will be a blank window on the desktop.

### ISSUE THREAD

**Issue by jiayouzl** [billycastelli/Silicon-Info#11]
Under macOS 15, your program has a bug. After restarting the computer, there will be a blank window on the desktop.~

v1.0.3~

**Comment by ghost** [comment]
Can confirm !

<img width="1470" alt="Capture d’écran 2024-09-18 à 12 28 24" src="https://github.com/user-attachments/assets/0278b3e5-1434-4510-b6a2-fd8d1f1e0501">

**Comment by jiayouzl** [comment]
> Can confirm ! 
> 
> <img alt="Capture d’écran 2024-09-18 à 12 28 24" width="1470" src="https://private-user-images.githubusercontent.com/181958005/368530824-0278b3e5-1434-4510-b6a2-fd8d1f1e0501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjM5MTMsIm5iZiI6MTcyNjY2MzYxMywicGF0aCI6Ii8xODE5NTgwMDUvMzY4NTMwODI0LTAyNzhiM2U1LTE0MzQtNDUxMC1iNmEyLWZkOGQxZjFlMDUwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMjQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGVmY2Y4NWJhYWY1YWU1OTg2NGVlYTZjODI1OTc5NjNjMTFlMzM2NWRiN2E4NWQwOTZmNDkzNTg5MWI2M2MzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ySGu-TQQ3IGr0O69HFwr579kpwJzu2ggQpu1qNuJQQk">

**I referenced the author's related Swift code and developed one using Python 3. I will wait to see if the author updates it recently. If not, I will create a repository and release it.**

<img width="367" alt="iShot_2024-09-18_21 02 23" src="https://github.com/user-attachments/assets/39c3b227-32d5-433b-bd19-48b53b33e3ef">

<img width="335" alt="iShot_2024-09-18_21 02 37" src="https://github.com/user-attachments/assets/78c20eff-4ac5-4ffa-ac88-c9af6460022b">

**Comment by brokosz** [comment]
pretty sure this should still be open. it's not resolved here or in the MAS version

**Comment by pencilcheck** [comment]
still seeing it on sequoia
