### ISSUE TITLE
What is the license for this code?

### ISSUE THREAD

**Issue by jensenharris** [billycastelli/Silicon-Info#6]
Hi Billy, thanks for the great app.

What is the license for this code? I didn't see one attached to the repo. Wondering if I can fork and modify for my own use.

**Comment by billycastelli** [comment]
Hi Jensen,

Thanks! Feel free to fork and modify it however you please. I just added an [MIT License ](https://github.com/billycastelli/Silicon-Info/blob/main/LICENSE)to the repo.

Cheers!
